"use client";

import { useState } from "react";
import { Copy, Check, Download } from "lucide-react";

type PromptGeneratorProps = {
  generatedPrompt: string;
};

export default function PromptGenerator({
  generatedPrompt,
}: PromptGeneratorProps) {

  const [copied, setCopied] = useState(false);

  async function copyPrompt() {

    if (!generatedPrompt) return;

    await navigator.clipboard.writeText(generatedPrompt);

    setCopied(true);

    setTimeout(() => {
      setCopied(false);
    }, 2000);
  }

  function downloadPrompt() {

    if (!generatedPrompt) return;

    const blob = new Blob([generatedPrompt], {
      type: "text/plain",
    });

    const url = URL.createObjectURL(blob);

    const a = document.createElement("a");

    a.href = url;
    a.download = "promptforge-prompt.txt";

    a.click();

    URL.revokeObjectURL(url);
  }

  return (
    <section className="mt-20 mb-20 flex justify-center px-6">

      <div className="w-full max-w-5xl rounded-3xl border border-purple-500/30 bg-white/5 p-8 shadow-2xl shadow-purple-900/20 backdrop-blur-xl">

        <div className="flex flex-col gap-6 md:flex-row md:items-center md:justify-between">

          <div>

            <h2 className="text-3xl font-bold text-white">
              ✨ AI Generated Prompt
            </h2>

            <p className="mt-2 text-gray-400">
              Professional prompt generated by PromptForge AI
            </p>

          </div>

          <div className="flex gap-3">

            <button
              onClick={copyPrompt}
              disabled={!generatedPrompt}
              className="flex items-center gap-2 rounded-xl border border-purple-500 bg-purple-500/10 px-5 py-3 text-white transition hover:bg-purple-600 disabled:cursor-not-allowed disabled:opacity-40"
            >

              {copied ? (
                <>
                  <Check size={18} />
                  Copied
                </>
              ) : (
                <>
                  <Copy size={18} />
                  Copy
                </>
              )}

            </button>

            <button
              onClick={downloadPrompt}
              disabled={!generatedPrompt}
              className="flex items-center gap-2 rounded-xl border border-blue-500 bg-blue-500/10 px-5 py-3 text-white transition hover:bg-blue-600 disabled:cursor-not-allowed disabled:opacity-40"
            >
              <Download size={18} />
              Download
            </button>

          </div>

        </div>

        <div className="mt-8 min-h-[320px] max-h-[500px] overflow-y-auto rounded-2xl border border-white/10 bg-black/40 p-6">

          {generatedPrompt ? (

            <pre className="whitespace-pre-wrap font-mono text-[15px] leading-8 text-gray-300">
              {generatedPrompt}
            </pre>

          ) : (

            <div className="flex h-[250px] flex-col items-center justify-center text-center">

              <div className="mb-4 text-5xl">
                ✨
              </div>

              <h3 className="text-xl font-semibold text-white">
                No Prompt Generated Yet
              </h3>

              <p className="mt-3 max-w-md text-gray-500">
                Upload an image above, choose an optimization mode,
                and PromptForge will generate a professional AI prompt
                for you instantly.
              </p>

            </div>

          )}

        </div>

      </div>

    </section>
  );
}